# Generated by Django 3.2 on 2023-02-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product1',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
