# Generated by Django 3.2 on 2023-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_select_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photographer',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
